on:
  push:
    branches: [main]
  workflow_dispatch:
name: Minify JSON
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout files
      uses: actions/checkout@v2
    
    - name: Minify JSON
      uses: StefanEnsmann/Minify-JSON-Action@1.1.0
      with:
        input_file: web_accounts_list.json
        output_file: web_accounts_list-min.json
